CREATE TABLE `T_EMPLOYEE` (
  `EMP_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `EMP_NAME` VARCHAR(100) NOT NULL,
  `EMP_DEPT` VARCHAR(100) NOT NULL,
  `EMP_EXP` INT(11) NOT NULL,
  `EMP_SALARY` DOUBLE NOT NULL,
  `EMP_STATUS` VARCHAR(35) DEFAULT NULL,
  PRIMARY KEY (`EMP_ID`)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;

CREATE TABLE `T_USER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `EMAIL` VARCHAR(255) DEFAULT NULL,
  `AGE` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;
